spring:
  application:
    name: warehouse-service

  datasource:
    url: jdbc:postgresql://localhost:5433/warehouse-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop  # Изменено с validate на create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # dialect: org.hibernate.dialect.PostgreSQLDialect  # Закомментировано, т.к. Spring сам определяет

  liquibase:
    enabled: false  # Отключаем Liquibase на время разработки

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: warehouse-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: orderEvent:com.example.warehouse_service.dto.OrderEvent

server:
  port: 8082

logging:
  level:
    com.example.warehouse_service: DEBUG
    org.springframework.transaction: DEBUG